### ISSUE TITLE
Imagem na página inicial clicavel

### ISSUE THREAD

**Issue by marcelobohn** [Digitaldesk-Labs/BemVindo#56]
**Necessidade**
A imagem com a foto da equipe deve ser 'clicável' e abrindo a página de acordo com a área de cada indivíduo. 

**Detalhamento**
A imagem que hoje aparece na entrada no site, contem todos da equipe, alterar o comportamento para permitir o clique sobre a imagem e direcionar a página da pessoa que recebeu o clique. Analisar qual o comportamento quando não clicar sobre uma pessoa.

**Comment by luantoni** [comment]
Responsável pelo código: Valéria e Luisa
Estilização da página: Valéria, Luisa, Bruno Klein e Geison.

**Comment by GeisonCamara** [comment]
Foi feito o PR desta tarefa por mim a pedido da Luisa.
