### ISSUE TITLE
Permitir navegação direta entre as páginas

### ISSUE THREAD

**Issue by marcelobohn** [Digitaldesk-Labs/BemVindo#57]
**Problema**
Hoje para conseguir sair da página de um integrante e ir para outra é obrigatório voltar a página inicial, torna a navegação com complicada. É necessário implementar um recurso que possibilite a navegação direta entre as páginas.

**Detalhamento**
Implementar uma barra de menu que será exatamente a mesma entre todas as páginas que permita o acesso direto e também o retorno a página inicial

**Comment by luantoni** [comment]
Responsável pelo código: Geison
