### ISSUE TITLE
Deploy automatizado

### ISSUE THREAD

**Issue by marcelobohn** [Digitaldesk-Labs/BemVindo#90]
**Necessidade**
O deploy do projeto é feito de forma manual, verificar se através de uma _Task_ do *Gulp* seja possível fazer o deploy automatizado.

**Solução**
É necessária uma pesquisa para avaliar a viabilidade de implementação desse recurso, então será discutido em reunião para definição do que será feito.

**Comment by GuinterW** [comment]
Informações referentes a deploy:
O que é deploy?
Pode ser, entre várias definições possíveis, colocar um projeto em produção, ou seja, dar upload para um servidor de verdade(site). Também pode ser um conceito para instalar a aplicação em um lugar a fim de disponibilizar ela para seu público alvo ou para a realização de testes.

Qual a vantagem de fazer deploy automaticamente?
A principal vantagem da automatização é a redução de custos, que se dá principalmente pela redução da carga horária dos profissionais que antes faziam horas extras somente para a realização do deploy manualmente. Além disso, um deploy automático realizado por uma ferramenta bem customizada em prol dos interesses da empresa é quase que uma garantia de um deploy seguro e com alto nível de eficiência. Por fim, a quantidade de bugs tende a reduzir drasticamente a partir da automatização do deploy.

O que é necessário para fazer o processo de automatização do deploy através do Gulp?
Os sites a seguir trazem detalhadamente os passos de como automatizar o processo de deploy:
http://imasters.com.br/front-end/gulp-e-ftp-atualizar-um-site-on-the-fly/?trace=1519021197&source=single

http://pauloluan.github.io/blog/blog/2015/04/29/fazendo-deploy-de-aplicacoes-glp-no-gh-pages/
